repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3.9
        args: [
          --line-length=127,
          --profile=black
        ]
  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=127]
  # We can safely ignore flake8 warnings that pylint catches.
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
        ]
        language_version: python3.9
        args: [
          --max-line-length=127,
          '--ignore=D105,D200,W503,F401,F811'
        ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          --max-line-length=127,
          '--disable=logging-fstring-interpolation,logging-not-lazy',
          '--good-names=_,rc,ti,ip,l3',
          '--load-plugins=pylint_pytest'
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        additional_dependencies: [types-PyYAML, types-requests, types-setuptools]
